# Generated by Django 2.2.7 on 2019-12-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuario', '0002_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad',
            new_name='costopresupuestado',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precioProducto',
            new_name='precioproducto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombreProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='nombreproducto',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='nota',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
